### ISSUE TITLE
Add page about useful method pragmas

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-open-documentation/pharo-wiki#18]
- `<script>` and `<script: '1 inspect'>`
- `<example>`

others?

**Comment by jecisc** [comment]
It should go in the "CoolToKnowForBeginners" page

**Comment by olekscode** [comment]
I think it should be a separate page. Or maybe "CoolToKnowForBeginners" should be a folder with this page in it. Otherwise if you put everything inside a single "CoolToKnowForBeginners" page, it will be too big. It would be cool to have description of every pragma with examples and instructions on how to define your own pragmas.

**Comment by jecisc** [comment]
After talking with Oleks we think that we should have a page dedicated to Pragmas in general and a subpart with the useful pragmas that are already used in Pharo.

**Comment by juliendelplanque** [comment]
This has been done and integrated.
